### ISSUE TITLE
Show point when bought on tradingview map

### ISSUE THREAD

**Issue by gmverdon** [gmverdon/TradingBot#10]
Need to look into this if this is supported by TradingView

**Comment by gmverdon** [comment]
Not sure if this is possible. @rafaelklaessen can you maby take a look at this?

**Comment by rafaelklaessen** [comment]
I'll take a look at this. But it really depends on TradingView

**Comment by gmverdon** [comment]
What is the progress on this issue?

**Comment by rafaelklaessen** [comment]
I forgot to update you

**Comment by rafaelklaessen** [comment]
But the API just doesn't allow this
