### ISSUE TITLE
Module not found: Can't resolve 'binance-api' in '/root/TradingBot/src/scenes/Home'

### ISSUE THREAD

**Issue by pipinoloco** [gmverdon/TradingBot#18]
hello it cant compile Module not found: Can't resolve 'binance-api' in '/root/TradingBot/src/scenes/Home'

**Comment by gmverdon** [comment]
Have you tried to run 'npm install' again?

**Comment by pipinoloco** [comment]
yes, tested on ubuntu vps and debian vps same mistake.

**Comment by rafaelklaessen** [comment]
@gmverdon Would it be an option to just publish your binance-api to NPM as well, like `gmverdon-node-binance-api`?
That'd would fix this problem permanently.

**Comment by gmverdon** [comment]
I have updated the module and module references. @pipinoloco could you try pulling the updated project and run 'npm install' again?

**Comment by pipinoloco** [comment]
yes, now it says 
Compiled with warnings.

./src/components/Header/index.js
  Line 2:  'NavLink' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by rafaelklaessen** [comment]
That is fine. @gmverdon will look at this warning but it should already work.

**Comment by gmverdon** [comment]
I will look at this warning, but as @rafaelklaessen pointed out the warning does not hamper the compilation. If you have any further issues, do not hesitate to comment, however for now I will close this issue.
